### Get all orders
GET http://localhost:3000/api/orders

### Get single order by ID
GET http://localhost:3000/api/orders/your-order-id-here

### Create new order
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "userId": "67925c498af5db2d489a54eb",
    "orderItems": [
        {
            "productId": "67855514e29c4baec82d950b",
            "quantity": 2,
            "unitPrice": 30.00,
            "subtotal": 60.00
        },
        {
            "productId": "678965973b4fc9d467168854",
            "quantity": 1,
            "unitPrice": 49.99,
            "subtotal": 49.99
        }
    ]
}

### Update order
PUT http://localhost:3000/api/orders/your-order-id-here
Content-Type: application/json

{
    "status": "completed",
    "orderItems": [
        {
            "productId": "product-id-1",
            "quantity": 3,
            "unitPrice": 29.99,
            "subtotal": 89.97
        }
    ]
}

### Delete order
DELETE http://localhost:3000/api/orders/your-order-id-here