
GET http://localhost:3000/api/users

### obtener un usuario por id 

GET http://localhost:3000/api/users/1   

### crear un nuevo usuario

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "agustina@gmail.com" ,
    "password": "contra123",
    "privilege": "cliente",
    "firstName": "Agustina",
    "lastName":"Chemele",
    "phone": "3044987654",
    "street": "Mendoza",
    "streetNumber": "1200",
    "city": "654cecadf2319d36d23f1020"
}
