### obtener todos los productos

GET http://localhost:3000/api/products

### obtener un producto por id ----- 1 es el id del producto

GET http://localhost:3000/api/products/1   

### crear un nuevo producto

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Tamo loco" ,
  "description":"Una cartera imprescindible para tu colección, con una correa ajustable y un diseño perfecto.",
  "price": 120000,
  "stock": 5,
  "image": "https://equipovallejo.vtexassets.com/arquivos/ids/232122-800-auto?v=638161505849100000&width=800&height=auto&aspect=true",
  //"image": "../../uploadsProductsPhotographs/Cartera1.jpg",
  "category": "654ced3bbaab1b1922b95bfd",
  "supplier": "654cece3f2319d36d23f1021"
}

### modificar un producto (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/products/1
Content-Type: application/json

### modificar un producto (PATCH  - recurso parcial)

PATCH http://localhost:3000/api/products/1
Content-Type: application/json


### borrar un producto

DELETE http://localhost:3000/api/products/654e1c9e0750690b678af05d