### obtener todos los productos

GET http://localhost:3000/api/products

### obtener un producto por id ----- 1 es el id del producto

GET http://localhost:3000/api/products/1   


id city 654930bdaf270c0d88ad8d66
### crear un nuevo producto

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Delicate" ,
  "description":"Una cartera imprescindible para tu colección, con una correa ajustable y un diseño perfecto.",
  "price": 120000,
  "stock": 5,
  "image": "https://drive.google.com/file/d/1p1Ypb9oFli5KFF7gwBaMdYMoDEgpJ_Mx/view?usp=sharing",
  "category": "654baf282aed6214eed43aa3",
  "supplier": "654bb0e52aed6214eed43aa6"

}

### modificar un producto (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/products/1
Content-Type: application/json

### modificar un producto (PATCH  - recurso parcial)

PATCH http://localhost:3000/api/products/1
Content-Type: application/json


### borrar un producto

DELETE http://localhost:3000/api/products/1