### obtener todos los productos

GET http://localhost:3000/api/products

### obtener un producto por id ----- 1 es el id del producto

GET http://localhost:3000/api/products/1   


### crear un nuevo producto

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Delicate" ,
  "description":"Una cartera imprescindible para tu colección, con una correa ajustable y un diseño perfecto.",
  "price": 120000,
  "stock": 5,
  "image": "Cartera1.jpg",
  "category": "654ced3bbaab1b1922b95bfd",
  "supplier": "654cece3f2319d36d23f1021"
}

### modificar un producto (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/products/1
Content-Type: application/json

### modificar un producto (PATCH  - recurso parcial)

PATCH http://localhost:3000/api/products/1
Content-Type: application/json


### borrar un producto

DELETE http://localhost:3000/api/products/1